### ISSUE TITLE
Update product build ADO pipeline to push zips/tars to github

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/go-sqlcmd#106]
Today our product build pipeline generates the various linux/windows binary archives but we have to manually upload them to the release. Let's add a service connection to github in our ADO and modify the build pipeline to push the binary archives to github automatically.

**Comment by shueybubbles** [comment]
@apoorvdeshmukh  can this be closed?

**Comment by apoorvdeshmukh** [comment]
Yes.
