### ISSUE TITLE
-v does not work when SQL file has comments

### ISSUE THREAD

**Issue by zijchen** [microsoft/go-sqlcmd#114]
I have a SQL file like this
```tsql
-- Comment
DROP DATABASE [$(DbName)]
```
When I run `sqlcmd -i input.sql -v DbName=MyDatabase`, I get error 
> Database '$(DbName)' does not exist. Make sure that the name is entered correctly.

If I remove the comment on line 1, the script executes successfully.

This used to work with the old sqlcmd.

**Comment by zijchen** [comment]
It also works if the comment is after the line where the SQLCMD variable is, so the issue is only if the comment precedes the SQLCMD variable.

**Comment by apoorvdeshmukh** [comment]
I could not reproduce this when the mentioned sql statements were the only SQL statements in the file.
I however could reproduce it with sql file similar to
```
-- Comment
CREATE DATABASE [$(Dbname)]
USE [$(Dbname)]
USE master
DROP DATABASE [$(DbName)]
```
On console
```
>.\sqlcmd.exe -i input.sql -v Dbname=T213
Msg 911, Level 16, State 1, Server LAPTOP-VPBI3ASB, Line 3
Database '$(Dbname)' does not exist. Make sure that the name is entered correctly.
```
