### ISSUE TITLE
Trusted connection does not work

### ISSUE THREAD

**Issue by randomizedthinking** [microsoft/go-sqlcmd#124]
There is no problem if I use the `sqlcmd` from the mssql-tools package to connect the server. Yet, the same setting does not work with `go-sqlcmd`.

Anywhere we can find relative complete document on `go-sqlcmd`?

**Comment by shueybubbles** [comment]
Once go-mssqldb driver merges the PR https://github.com/microsoft/go-mssqldb/pull/35 to enable kerberos auth on Linux, sqlcmd will pick up that version. Or are you referring to some other trusted connection type?

**Comment by randomizedthinking** [comment]
Thanks, the problem is now resolved.
