### ISSUE TITLE
Invalid Packet size value returned from server

### ISSUE THREAD

**Issue by dmittelstaedt** [microsoft/go-sqlcmd#129]
If I try to connect to MSSQL Server with sqlcmd 0.8.1 I get the following error:
```
bash-5.1# sqlcmd -S mssqlserver:3636 -U user 
Password:
Invalid Packet size value returned from server (? ??): strconv.Atoi: parsing "?\u3000??": invalid syntax
```

```
bash-5.1# sqlcmd -S mssqlserver:3636 -U user -a 1024
Password:
TLS Handshake failed: cannot read handshake packet: invalid packet size, it is longer than buffer size
```

```
bash-5.1# sqlcmd -S mssqlserver:3636 -U user --driver-logging-level 64 -a 1024
Password:
TLS Handshake failed: cannot read handshake packet: invalid packet size, it is longer than buffer size
```

```
bash-5.1# sqlcmd -S mssqlserver:3636 -U user --driver-logging-level 64
Password:
DRIVER:got token tokenEnvChange
DRIVER:got token tokenInfo
DRIVER:got INFO 5701 ??????? ???????? ??????? ?? ?????????
DRIVER:got token tokenEnvChange
DRIVER:got token tokenEnvChange
DRIVER:got token tokenInfo
DRIVER:got INFO 5703 ??????? ???????? ??????? ?? ???????????
DRIVER:got token tokenLoginAck
DRIVER:got token tokenEnvChange
Invalid Packet size value returned from server (? ??): strconv.Atoi: parsing "?\u3000??": invalid syntax
```

Am I doing something wrong?

sqlcmd is running in a container on:
```
bash-5.1# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.2
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

bash-5.1# uname -a
Linux sqlcmdtest 4.18.0-305.57.1.el8_4.s390x #1 SMP Tue Jul 5 17:49:51 EDT 2022 s390x Linux
```

**Comment by shueybubbles** [comment]
What version of SQL Server?

**Comment by dmittelstaedt** [comment]
`select @@version;` returns the following

Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)   Jul 19 2021 15:37:34   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: )

**Comment by shueybubbles** [comment]
Can sqlcmd running on some other distro connect to the same server? I've not used Alpine myself.  I've seen no such issues with Ubuntu or Windows. 
Is it running on an ARM processor?

**Comment by dmittelstaedt** [comment]
Currently it is not possible to run sqlcmd on an other architecture. Alpine Linux is running as pod in OpenShift and we also tested Ubuntu as Base Image for sqlcmd, with no luck. It returns the same error message.
OpenShift/sqlcmd is running on IBM Z, s390x architecture.

**Comment by shueybubbles** [comment]
in the meantime, you could build it yourself from source with GOARCH=s390x.
