### ISSUE TITLE
Cannot unmarshal DNS message

### ISSUE THREAD

**Issue by KSchlobohm** [microsoft/go-sqlcmd#133]
Unable to use `sqlcmd` to connect to Azure SQL Database from WSL2 Ubuntu distro.

Recieving the following error when trying to connect
```
error: lookup iqurlpv8xu4eq-sql-server.database.windows.net on xxx.xxx.xxx.xxx:53: cannot unmarshal DNS message
```

This appears to be:
* A [known issue](https://github.com/microsoft/WSL/issues/7642) with WSL
* That was [patched in go-lang](https://github.com/golang/go/issues/51127)

Expected `sqlcmd` to connect to Azure SQL Database

**Comment by shueybubbles** [comment]
try the current v0.9.1 release, it's built with go 1.18

**Comment by KSchlobohm** [comment]
that fixed the issue for me. thanks!
