### ISSUE TITLE
About release process

### ISSUE THREAD

**Issue by chenrui333** [microsoft/go-sqlcmd#137]
We have a [new formula PR for adding sqlcmd](https://github.com/Homebrew/homebrew-core/pull/109882), but found the release commits are pointing the same one, can I get some clarifications about the release process (i.e. is that intentional)? Thanks a lot.

**Comment by stuartpa** [comment]
> We have a [new formula PR for adding sqlcmd](https://github.com/Homebrew/homebrew-core/pull/109882), but found the release commits are pointing the same one, can I get some clarifications about the release process (i.e. is that intentional)? Thanks a lot.

Is this about a 0.9.2 and a 0.9.3 release?  @apoorvdeshmukh were you testing releases and created these temporarily?

**Comment by Charles-Gagnon** [comment]
FYI @shueybubbles - if you hadn't found this out already tags aren't a per-branch thing. They're similar to branches themselves in that they point to a specific commit - but that commit can be anywhere in the tree (so you could have a tag pointing to a commit on main, or a commit on a feature branch)

(and a release is just a tag with some extra metadata associated with it, but that's a Github thing not a git thing)
