### ISSUE TITLE
Add a command line canonicalizer to internally mask funky back-compat switches  

### ISSUE THREAD

**Issue by stuartpa** [microsoft/go-sqlcmd#154]
Some of the original sqlcmd (ODBC base) command line switches are completely non-standard by modern standards, such as  -x1 / -k1 -k2 etc and therefore not supportable by any modern CLI framework (such as Kong or Cobra), rather than try to hack these CLI frameworks, add a canonicalizer very early in process start-up that looks for these odd command line switches and re-writes them into a standard form, and then passes args in standard form into the CLI framework Cobra/Kong.

**Comment by stuartpa** [comment]
Another PR comment related to this, recording here:

"i suspect some version of this code is permanent. We aren't likely to reproduce all the legacy switches in the new CLI are we? Perhaps we should use an environment variable to only allow modern mode where it uses query as the default command but only with whatever switches that command supports." - David

"I think we can solve the problem of the legacy switches by writing a small "canonicalizer" called at the start of main, which scans through the supplied args, and modifies them to be parsable by Cobra, then call cobra.command.SetArgs to override what's passed in from env." - Stuart

**Comment by shueybubbles** [comment]
i think we can make these work with Cobra without a special case.
