### ISSUE TITLE
Modern CLI is getting invoked in spite of missing verbs

### ISSUE THREAD

**Issue by apoorvdeshmukh** [microsoft/go-sqlcmd#183]
@JyotikaGargg and I found this issue in [main.go](https://github.com/microsoft/go-sqlcmd/blob/41c71c2ee2f4e0f27dcde77861de86282135c5c3/cmd/modern/main.go#L52) where we read the 2nd argument even if os.Args contains just 1 argument i.e. when no argument is specified to sqlcmd.exe

```golang
if len(os.Args) > 0 {
		if rootCmd.IsValidSubCommand(os.Args[1]) {
			isNewCliCommand = true
		}
	}
```

```
\go-sqlcmd\cmd\modern>go build -o sqlcmd.exe
\go-sqlcmd\cmd\modern>.\sqlcmd.exe
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.isFirstArgModernCliSubCommand(...)
        C:/Users/apdeshmukh/git/go-sqlcmd/cmd/modern/main.go:53
main.main()
        C:/Users/apdeshmukh/git/go-sqlcmd/cmd/modern/main.go:41 +0x245
```

**Comment by stuartpa** [comment]
Yeah, I saw this as well (have a fix for it in my draft PR).  Thanks for fixing it
