### ISSUE TITLE
Parsing error with database name

### ISSUE THREAD

**Issue by nycdotnet** [microsoft/go-sqlcmd#197]
Hello,

Thank you for addressing the issue with the `__` variable names yesterday.  Our script generated from SQL Server Data Tools is now parsing further with go-sqlcmd, but not completely yet.  There appears to be another gap (and one oddity that I need to think about before complaining about it).

The script contains a section similar to this fairly boiled-down repro:

```
GO
:setvar DatabaseName "MyTestDatabaseGitHub20230120"

GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL)
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END
GO

CREATE DATABASE [$(DatabaseName)]

GO
USE [$(DatabaseName)]
GO
```

When I save the above script to a `.sql` file and run it with go-sqlcmd, using `./sqlcmd -b -i testdb.sql -U SA`, this script returns the following error:

```
Msg 105, Level 15, State 1, Server c6c5144e6044, Line 2
Unclosed quotation mark after the character string ') IS NOT NULL)
BEGIN
    ALTER DATABASE [MyTestDatabaseGitHub20230120]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [MyTestDatabaseGitHub20230120];
END'.
```

When run with legacy sqlcmd using the same options, the output looks like the below, which is the desired output, and the database is dropped and created.  (note the very first time you run it, it won't output the first four lines because it does not enter the if block):

```
2023-01-20 16:56:50.44 spid52      Setting database option SINGLE_USER to ON for database 'MyTestDatabaseGitHub20230120'.
2023-01-20 16:56:50.82 spid52      Starting up database 'MyTestDatabaseGitHub20230120'.
2023-01-20 16:56:50.87 spid52      Parallel redo is started for database 'MyTestDatabaseGitHub20230120' with worker pool size [1].
2023-01-20 16:56:50.90 spid52      Parallel redo is shutdown for database 'MyTestDatabaseGitHub20230120' with worker pool size [1].
Changed database context to 'MyTestDatabaseGitHub20230120'.
```

Please let me know if I can provide any additional information.  I believe this is some sort of parsing/replacement bug but my Go skills are insufficient to create a failing unit test.

**Comment by shueybubbles** [comment]
i get a different error. Are you running on Linux or Windows?
When I copy out your sample to .sql file and run it, the SQL batches look like this:
```sql

IF (DB_ID(N'MyTestDatabaseGitHub20230120') IS NOT NULL)
BEGIN
    ALTER DATABASE [MyTestDatabaseGitHub20230120]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [MyTestDatabaseGitHub20230120];
END

CREATE DATABASEMyTestDatabaseGitHub20230120e)]

```

My version is somehow missing a space between DATABASE and the variable value and has an extra ), so there's some off-by-one bug somewhere in the variable replacement code.
I will investigate, thx

**Comment by nycdotnet** [comment]
I am running it in a Linux Docker container on Windows x64.  My intended target is Linux on Arm (we need go-sqlcmd to support Dockerized SQL Server for devs on M1 Macs).  I will send you a Dockerfile on Monday demonstrating.  In fact I was considering opening a PR to document how to get go-sqlcmd running in a container, so maybe I will just do that.

**Comment by nycdotnet** [comment]
@shueybubbles I put a dockerfile and script [here](https://github.com/microsoft/go-sqlcmd/pull/198) with an even simpler repro script.  I hope you find it useful.  Thank you!!

**Comment by shueybubbles** [comment]
@nycdotnet I should have a fix soon. in the meantime I think you can work around the bug by having at least a comment or other code as the first line of a batch instead of having a line with a variable as the first line of the batch.

**Comment by nycdotnet** [comment]
Excellent thank you.  Since the scripts we're running are generated by sqlpackage.exe, they're not really changeable except via regex.  I guess I could replace all `GO` lines with `GO\n--comment here` or something, but if you're on to the cause it's fine for us to just wait a bit.  Many thanks for being so responsive and for creating and releasing this project.

**Comment by shueybubbles** [comment]
This issue is a symptom of several bugs in batch parsing, mostly related to handling of line feed insertions. The ODBC sqlcmd treats file input somewhat differently than console input and so should we.
These are the rules as I understand them from experimenting with ODBC sqlcmd:

1. If there's no line feed on the last line of the file, don't send one.
2. Always send a line feed after each typed line in interactive mode.,
3. Ignore blank lines even if they are inside a quote

eg:
```
E:\git>sqlcmd
1> select '200
2~
3~
4~
5~ '
6> go

-----------
200
```
Notice the result string has no carriage returns in it.

This input file:
```
select 'line1

line2
'

/* line 1 comment

line 2 comment

*/

```
Produces this batch on the server:

```sql
select 'line1
line2
'
/* line 1 comment
line 2 comment
*/
```

The buggy code impacts variables because it inserts a line feed in the buffer before doing the math to calculate the offsets of the variable in the buffer.

**Comment by nycdotnet** [comment]
Thank you for investigating- do you need anything else from me?  I can provide you with one of our full db schema files if that's would be helpful.

**Comment by shueybubbles** [comment]
@nycdotnet  are you able to build my branch https://github.com/microsoft/go-sqlcmd/tree/shueybubbles/197 from source and test the binary with your scripts? 
there are `build.sh` and `build.cmd` files in the `build` folder.

**Comment by nycdotnet** [comment]
oh amazing - will give it a shot.

**Comment by nycdotnet** [comment]
OK the good news is that this is a significant improvement.  Three of our database scripts go in perfectly with this version, but the fourth has a challenge that appears to be around a particularly wonky query.  I am going to see if I can create a simple repro for that additional issue.  Thanks so much!!

**Comment by nycdotnet** [comment]
OK I can get the bug to manifest on this script when saved to a .sql file:

```sql
use [master]
go

CREATE PROCEDURE [dbo].[MySproc]
AS
BEGIN

SELECT
    [person's birth date] = 'apple',
	[person's hire date] = 'banana',
	[person's attribute no. 1] = ''

END
GO
```

It works with legacy ODBC sqlcmd, and returns this output when used with go-sqlcmd (the version in your branch, @shueybubbles ). Note this may be a unrelated issue to the one(s) you fixed.

```
./sqlcmd/sqlcmd -i ./sqlcmd/this-one-bombs2.sql -U SA
Changed database context to 'master'.
Msg 102, Level 15, State 1, Server buildkitsandbox, Line 10
Incorrect syntax near 'GO'.
```

**Comment by nycdotnet** [comment]
Note - this is obviously cursed SQL syntax, but it is supported by SQL Server and legacy `sqlcmd`.  It also breaks in Goland's SQL syntax highlighting, so it's certainly not pretty!!!!

**Comment by shueybubbles** [comment]
oh it's probably the `'` inside `[]`

**Comment by shueybubbles** [comment]
fix pushed, give it a try

**Comment by nycdotnet** [comment]
Thanks will investigate in the morning.  Much appreciated.

**Comment by nycdotnet** [comment]
Well done!  More progress but not there yet for my script but I this appears to be a different issue with more cursed sql involving `goto` and labels.

This script repros the issue:

```
if (1=2)
BEGIN
    goto Exit_Error
end
else
begin
    print 'phew!'
    goto Exit_Happy
end

Exit_Error:
  RAISERROR('something very strange is happening', 16, 1)

Exit_Happy:
    -- everything is fine
```

On legacy ODBC SQLCMD this outputs:

`phew!`

On go-sqlcmd, this outputs:

```
Sqlcmd: Error: Syntax error at line 11 near command 'EXIT'.
Sqlcmd: Error: Syntax error at line 14 near command 'EXIT'.
Msg 133, Level 15, State 1, Server buildkitsandbox, Line 11
A GOTO statement references the label 'Exit_Happy' but the label has not been declared.
Msg 133, Level 15, State 1, Server buildkitsandbox, Line 11
A GOTO statement references the label 'Exit_Error' but the label has not been declared.
```

**Comment by nycdotnet** [comment]
by the way I did just rename all of the offending labels in our script file (believe it or not we have several that begin with comand names - exit and rollback in particular), and after doing so, this latest build of go-sqlcmd was able to build our database completely, so this is hopefully the last known blocker for us.  Just renaming labels (and the corresponding gotos) from `Exit_Error` to `zExit_Error` fixed it, so it really does appear to just be a bug with labels that begin with command keywords.  Thanks @shueybubbles  !!

**Comment by shueybubbles** [comment]
cool will get that fixed tomorrow. I guess the regex we're using matches `_` as a space or something.
