### ISSUE TITLE
Add DAC support (-A) for go-sqlcmd

### ISSUE THREAD

**Issue by stuartpa** [microsoft/go-sqlcmd#200]

**Comment by diego-deriv** [comment]
Hi this was supported by the `mssql-tools/bin/sqlcmd`, it will be really helpful to have this feature also for `go-sqlcmd`

**Comment by shueybubbles** [comment]
@diego-deriv if you are using the standard DAC port on SQL server I think you can just use `server,1434` as the server name. 
To support non-default ports/instance names, we'll need to augment the go-mssqldb driver to support the `admin` protocol. 
I opened https://github.com/microsoft/go-mssqldb/issues/108
