### ISSUE TITLE
Support customized T/SQL database name with --using flag

### ISSUE THREAD

**Issue by stuartpa** [microsoft/go-sqlcmd#216]
It would be nice for people to be able to set the T/SQL name of their database when using the --using flag, at the moment the name is set to the .bak file name, e.g. AdventureWorksLT.  The suggestion is to use the following "," format, https://aka.ms/AdventureWorksLT.bak,adventure_works, where the name of the database comes after the comma, e.g. adventure_works in this case.

**Comment by apoorvdeshmukh** [comment]
I suppose the [,DBNAME] is optional here. 
So we set the DBNAME as filename without extension if DBNAME is not provided by user and set it to the given name otherwise.

**Comment by stuartpa** [comment]
> I suppose the [,DBNAME] is optional here. So we set the DBNAME as filename without extension if DBNAME is not provided by user and set it to the given name otherwise.

Yes, that's it
