### ISSUE TITLE
Behavior of sqlcmd (with no sub-commands / or flags) moving forward 

### ISSUE THREAD

**Issue by stuartpa** [microsoft/go-sqlcmd#217]
If `sqlcmd` is run with no sub-commands or flags, the original behavior is to connect to the local port 1433 instance using trusted auth.

If a user is using go-sqlcmd, this behavior continues to work, however, if the user then goes onto use the modern CLI options, and does a `sqlcmd create`, which creates a current-context.  Should `sqlcmd` now connect to the current context (which would be a container), rather than the localhost on port 1433.  

Because the user has opted in to the modern behavior, with a sqlcmd create, it feels reasonable, and probably confirming to POLA, for `sqlcmd` to use the current context. (which becomes the same behavior as `sqlcmd query`).

**Comment by shueybubbles** [comment]
If the user has created a config context file, I agree it should default to using the default context and have `query` as the default verb. This will be more helpful when we add some more useful flags to `query`.
