### ISSUE TITLE
Help Summary correction

### ISSUE THREAD

**Issue by apoorvdeshmukh** [microsoft/go-sqlcmd#226]
Creating this issue to correct help text.

Issues:
1. `sqlcmd create mssql` prompts to accept-eula and then user has to enter `sqlcmd create mssql --acept-eula`. We should probably put --accept-eula in top level help to avoid typing the cmd again.
2. `sqlcmd remove` provides hint about how a mounted db can be removed but db name is not correct in the hint text. Needs to be corrected.

**Comment by stuartpa** [comment]
Fixed in #240
