### ISSUE TITLE
Provide some mechanism for user to set SQLCMDPASSWORD

### ISSUE THREAD

**Issue by apoorvdeshmukh** [microsoft/go-sqlcmd#228]
To use sql server instance created by sqlcmd and to use it in sqlcmd backward compatibility mode, user needs to know SQLCMDPASSWORD.
We should internally set SQLCMDPASSWORD as env variable when `use-context` is applied.

**Comment by shueybubbles** [comment]
let's find a way to print individual components (by name?) of the current context or of a named context so calling scripts can put them in `set` commands

**Comment by shueybubbles** [comment]
@apoorvdeshmukh I think we can close this one, now that we implicitly use the current context when launching in backward compat mode. Or is there some other scenario to cover?

**Comment by apoorvdeshmukh** [comment]
No. We can close this one as the required scenario has been covered.
