### ISSUE TITLE
add-context --help :  #example is not working

### ISSUE THREAD

**Issue by JyotikaGargg** [microsoft/go-sqlcmd#229]
when you do : 
sqlcmd config add-context --help . 

It will show following example : 
sqlcmd config add-context --name context-name .

But this doesnot work , as gives following error : 
Error : Endpoint required to add context. Endpoint '' doesnot exist. Use --endpoint flag.

Expected Output : Example should be intuitive with all required fields.

**Comment by stuartpa** [comment]
Fixed in #240
