### ISSUE TITLE
When trying to connect too early to server , it prompts error

### ISSUE THREAD

**Issue by JyotikaGargg** [microsoft/go-sqlcmd#232]
When user trying to connect immediately after create command.
And then try to connect to ads , it throws error , because server is still not ready.

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/116666114/218731708-af4cc43c-9abc-469f-af9d-45a719fd5534.png)

**Comment by shueybubbles** [comment]
how long a connection timeout are you setting? If you make it long enough (like a minute+) does it work?

**Comment by shueybubbles** [comment]
please verify the repro scenario and see if the issue is a bug in ADS

**Comment by JyotikaGargg** [comment]
Seems to be an intermittent issue as it is no longer reproducible at any ADS version.
