### ISSUE TITLE
go-sqlcmd is failed to execute the tsql script contains any special charectors

### ISSUE THREAD

**Issue by prmadhes-msft** [microsoft/go-sqlcmd#239]
Below command is executing fine in SSMS but failed when executing like  sqlcmd -Sgo-sqlcmdvm -iF:\specialchar_sql.sql
--Create TestDB
USE TestDB;
GO

CREATE TABLE temptable(
   ID INT IDENTITY(1,1) PRIMARY KEY CLUSTERED ,
   Item  VARCHAR(50),
   value VARCHAR(50),
);
INSERT INTO dbo.temptable (  Item, value )
VALUES ( 'Item-A', '$(100.12)' );
GO 

Error details

C:\Users\sqladmin>sqlcmd -Sgo-sqlcmdvm -iF:\specialchar_sql.sql
Changed database context to 'TestDB'.
Sqlcmd: Error: Syntax error at line 10

![image](https://user-images.githubusercontent.com/62662636/219026470-bcc1d0a9-4e99-4c99-88f0-009783a9f428.png)

**Comment by shueybubbles** [comment]
using `$()` syntax doesn't work in sqlcmd because it's interpreted as a variable referenece. Disable variable evaluation.
