### ISSUE TITLE
SQLCMDPASSWORD vs SQLCMD_PASSWORD 

### ISSUE THREAD

**Issue by bweissman** [microsoft/go-sqlcmd#243]
the required env variable should use a consistent name.
Usually it is SQLCMDPASSWORD

but...

.\sqlcmd config add-user --name demo

HINT:
  1. Provide password in the **SQLCMD_PASSWORD** environment variable

**Comment by stuartpa** [comment]
I've added support for both SQLCMDPASSWORD and SQLCMD_PASSWORD.  EXENAME_ is the defacto standard (and is what Viper/Cobra the underlying golang packages support).  If both env vars are set I'll error out and ask the user to unset one.
