### ISSUE TITLE
delete-context deletes child objects

### ISSUE THREAD

**Issue by bweissman** [microsoft/go-sqlcmd#244]
when deleting a context, this also deletes the referenced endpoint and user.

this should not happen as I may just delete the context to recreate with a different endpoint or user. 

while there is a --cascade switch, it's defaulting to true and there is no (visible?) way of setting it to false

**Comment by bweissman** [comment]
using --cascade=false works (= is key here)

**Comment by stuartpa** [comment]
Sweet, is there anything more we need to do with this issue?

**Comment by bweissman** [comment]
It should probably be highlighted somewhere in docs or quick hint that the = is required (while it's not for most other parameters) but other than that  I think this is fine :)

**Comment by stuartpa** [comment]
Yes, great feedback.  I've added an example to the --help, so it is now:

C:\src\go-sqlcmd\cmd\modern>sqlcmd config delete-context --help
Delete a context

Usage:
  sqlcmd config delete-context [NAME] [flags]

Examples:
# Delete a context (including its endpoint and user)
  sqlcmd config delete-context --name my-context --cascade
  sqlcmd config delete-context my-context --cascade
# Delete a context (excluding its endpoint and user)
  sqlcmd config delete-context --name my-context --cascade=false
  sqlcmd config delete-context my-context --cascade=false

**Comment by bweissman** [comment]
Perfect!
