### ISSUE TITLE
installation docs wrong for linux

### ISSUE THREAD

**Issue by bweissman** [microsoft/go-sqlcmd#248]
when following the instuctions (https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16), you get (on ubuntu, using apt-get) the old sqlcmd :)

**Comment by stuartpa** [comment]
I'll be uploading the new sqlcmd to all the Linux package managers next week, then the new `sqlcmd create mssql` functionality will be available everywhere.
