### ISSUE TITLE
Deploy sqlcmd binary to appropriate package managers

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/go-sqlcmd#26]
Sqlcmd users should be able to install it on Linux the same way they install SQL Server.
What package managers should we target on Windows/Linux/Mac?
@dzsquared

**Comment by dzsquared** [comment]
Prior art on accepting licensing:

Debian install command line flag: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17

visual analog from SSMS: 
![image](https://user-images.githubusercontent.com/12227241/141183093-bfd74fd0-f618-49cd-aa66-c180667a2725.png)

**Comment by dzsquared** [comment]
priority towards ubuntu and centos, please

**Comment by tracker1** [comment]
A minimal Docker image would be nice as well, something that's easy to run as a packaged command, or copy the binary from into another container in Dockerfile.

**Comment by Hussar77** [comment]
> macOS would be [brew](https://docs.brew.sh/Adding-Software-to-Homebrew)
> Windows would be [choco](https://docs.chocolatey.org/en-us/create/create-packages)
> Not sure how to get added to Microsoft's packages repo for apt on Linux as seen in https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#ubuntu

The list looks good and I would support [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/) on Windows as well.

**Comment by tracker1** [comment]
Regarding Linux... 

Would suggest looking into appimage, flatpak (flathub) and snap.  Not sure if flatpak or appimage are good for cli apps. There are snap packages in ubuntu for cli apps.

The three are pretty much supported everywhere, appimage doesn't tether to a repo, would need to be in github releases... for flathub and snapcraft, probably quickest path to users being able to get to it.

**Comment by stuartpa** [comment]
Suggested rough ordering of implementation:

Docker, Apt (Debian/Ubuntu), RPM (Yum & Zypper) for (Centos, Fedora), MSI/Choco/Winget (Windows), Brew (Mac), Snap/Flatpack/AppImage (Ubuntu)

**Comment by stuartpa** [comment]
1st PR (of 5) out for RPM/Yum/Zypper/Centos/Fedora/Suse packages

https://github.com/microsoft/go-sqlcmd/pull/62

**Comment by grrlgeek** [comment]
@stuartpa Can this issue be closed now?

**Comment by stuartpa** [comment]
Yep.  We have sqlcmd in all the common package managers, will add more as users request them.
