### ISSUE TITLE
User's database default is not master or tempdb

### ISSUE THREAD

**Issue by airtank20** [microsoft/go-sqlcmd#284]
When using sqlcmd to start a container with a given database backup, the user's default database is changed to reflect the name of the database is restored in the create process.   If the database is later renamed that breaks sqlcmd because the original database is no longer present.  You either have to nuke/pave the container or know how to fix that from within sql. 

--1. run this
sqlcmd create mssql --using https://github.com/Microsoft/sql-server-samples/releases/download/wide-world-importers-v1.0/WideWorldImporters-Full.bak --accept-eula
--2. connect to the container via ADS
--3. run this
Alter database [WideWorldImporters-Full] set single_user with rollback IMMEDIATE;
Alter database [WideWorldImporters-Full] modify name = WideWorldImporters
Alter database [WideWorldImporters] set multi_user with rollback IMMEDIATE;
--4.  Back to sqlcmd, you cannot connect with the user_name/password

Suggested Fix:
alter login john with default_database = master
or
leave the user defaulted to master

**Comment by stuartpa** [comment]
We've added an Example to the `sqlcmd query --help` to help any user that runs into this to resolve it:

C:\src>sqlcmd query --help
Run a query against the current context

Usage:
  sqlcmd query [TEXT] [flags]

Examples:
...
# Set new default database
  sqlcmd query "ALTER LOGIN [stuartpa] WITH DEFAULT_DATABASE = [tempdb]" --database master
  
Also, #290 will have a full fix, in that the user will be able to specify the DB name in the --using flag, so don't need to rename later.

**Comment by stuartpa** [comment]
Fixed in 0.15.4 (--using now takes a ,tsql-db-name option), so rename not needed for this scenario.
