### ISSUE TITLE
Error - panic: Invalid encryption method ("" not in "none, dpapi")

### ISSUE THREAD

**Issue by yorek** [microsoft/go-sqlcmd#313]
With the latest 0.15.3 version I'm getting the following error:

```
> sqlcmd --version
panic: Invalid encryption method ("" not in "none, dpapi")

goroutine 1 [running]:
github.com/microsoft/go-sqlcmd/internal/secret.Decode({0xc0003904b0?, 0x44?}, {0x0, 0x0})
        D:/a/1/s/internal/secret/secret.go:50 +0x1e8
github.com/microsoft/go-sqlcmd/internal/config.GetCurrentContextInfo()
        D:/a/1/s/internal/config/context.go:107 +0x167
main.initializeEnvVars()
        D:/a/1/s/cmd/modern/main.go:83 +0xcf
main. Main()
        D:/a/1/s/cmd/modern/main.go:51 +0x20c
```

**Comment by stuartpa** [comment]
Simole fix is in the release notes.  (You have a sqlconfig file from an older release)

**Comment by yorek** [comment]
Got it, thanks!

**Comment by stuartpa** [comment]
From release notes fix is:

NOTE: For users of previous versions, if you have an old sqlconfig file, and get a "panic: Invalid encryption method", edit the ~/.sqlcmd/sqlconfig file and replace "password-encrypted: false" to "password-encryption: none".

You won't see this in the next dot release.

**Comment by yorek** [comment]
So, shouldn't be the config file now set to "v2"? That way you can easily raise an more friendly error if a previous version is detected. (or, even better, just automatically update). Using `winget` I have no way to get to the release notes.

**Comment by stuartpa** [comment]
This was just a bug, a file didn't get checked in off my machine.  But yes, in the future we need full version support for the sqlconfig schema.
