### ISSUE TITLE
Container not deleted with DELETE

### ISSUE THREAD

**Issue by way0utwest** [microsoft/go-sqlcmd#322]
I ran the DELETE command and thought I'd have the container removed, but it isn't. It also isn't re-used, so when I start with a new context, I get a new container.

I would expect if I lose context, that you also delete the container. Preferably, I'd have the option to specify if I delete a container and a way to specify which container to use on start.

**Comment by stuartpa** [comment]
sqlcmd does delete the container with:

```
sqlcmd delete
```

Per previous feedback from a user, we do allow the `sqlcmd delete` to succeed if the container has already been deleted.

If there is a situation where the container isn't being deleted, please run `sqlcmd delete --verbosity 4` and add the output to this issue.

**Comment by stuartpa** [comment]
Ah, I see the function:

userDatabaseSafetyCheck. 

Is being called... the error is:

"Unable to continue, a user (non-system) database ... is present"

Sqlcmd is failing the delete because it has detected a user database is present in the container.  It is outputting the following hint:

"Pass in the flag --force to override this safety check for user (non-system) databases"

This check gives the user a chance to confirm they really want to delete left over user data.

**Comment by way0utwest** [comment]
Would you like me to submit doc PRs for some of this? Either here and/or MS learn?

**Comment by felipeschneider88** [comment]
The error is crystal clear, you cannot DELETE with a user DB
```powershell
PS C:\Users\felip> sqlcmd delete
Current context is "mssql". Do you want to continue? (Y/N)
Y
Verifying no user (non-system) database (.mdf) files

HINT:
  1. If the database is mounted, run `sqlcmd query "use master; DROP DATABASE [<database_name>]"`
  2. Pass in the flag --force to override this safety check for user (non-system) databases

Error: Unable to continue, a user (non-system) database (/var/opt/mssql/data/testDB.mdf) is present
PS C:\Users\felip>
```

Maybe they can add a flag like **_--force_** to remove all the changes done by the user

**Comment by stuartpa** [comment]
> Would you like me to submit doc PRs for some of this? Either here and/or MS learn?

We are working on auto-generating documentation from `sqlcmd --help` for learn.microsoft.com.  This should help with the docs aspects (we do cover this safety check in sqlcmd delete --help examples)
