### ISSUE TITLE
Set context to on-premises SQL Server

### ISSUE THREAD

**Issue by way0utwest** [microsoft/go-sqlcmd#323]
I do like the idea of a context. However, what I'd like to do is set a context to a local instance of SQL Server, not a containerized version. I would prefer something like

sqlcmd config set-context mssql -S localhost -D AdventureWorks

**Comment by stuartpa** [comment]
Sure, this works no problems.  See `sqlcmd config --help` for an example of how to do this.
C:\>sqlcmd config --help
Modify sqlconfig files using subcommands like "sqlcmd config use-context mssql"

Usage:
  sqlcmd config [flags]
  sqlcmd config [command]

Examples:
# Add context for existing endpoint and user (use SQLCMD_PASSWORD or SQLCMDPASSWORD)
  SET SQLCMD_PASSWORD=<placeholderpassword>
  sqlcmd config add-user --name sa1434 --username sa
  SET SQLCMD_PASSWORD=
  sqlcmd config add-endpoint --name ep1434 --address localhost --port 1434
  sqlcmd config add-context --name mssql1434 --user sa1434 --endpoint ep1434

**Comment by way0utwest** [comment]
Then what I'd ask is better documentation. It's unclear what an endpoint is, nor it is clear that I ought to link the endpoint and context. Specifically, an example on https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16 that says this us for adding a local connection context. Same for the readme in the root of this repo.

I have verified this works.
