### ISSUE TITLE
Variables and colors don't work in context

### ISSUE THREAD

**Issue by way0utwest** [microsoft/go-sqlcmd#324]
I was trying to get colors to work in a context mode, but more disturbing is I can't use variables.
![2023-04-11 17_55_36-cmd](https://user-images.githubusercontent.com/3932940/231313399-1779b278-9f41-4a6e-876f-894d5205334d.png)

Repro: 
Run these from a CLI
1. create an instance - cmd create mssql --accept-eula --using https://aka.ms/AdventureWorksLT.bak
2. check things are running - sqlcmd query "select @@version
3. try to check colors - sqlcmd query ":color list"

**Comment by shueybubbles** [comment]
What if you put a space between `query` and `"` ?

**Comment by way0utwest** [comment]
Nope, doesn't work. I know you don't have access to results, but how do you with sqlcmd mode and not go-sqlcmd mode?
![2023-04-13 17_17_31-Variables and colors don't work in context · Issue #324 · microsoft_go-sqlcmd](https://user-images.githubusercontent.com/3932940/231902986-19c7bbd2-6518-4ddf-84b7-891622b1692a.png)

**Comment by shueybubbles** [comment]
oh it's
`:list color`

**Comment by shueybubbles** [comment]
example usage that works

```
10:13:08.52 e:\git\go-sqlcmd>set sqlcmdcolorscheme=emacs

10:13:14.09 e:\git\go-sqlcmd>sqlcmd query "select top (2) name from sys.objects
```

![image](https://user-images.githubusercontent.com/2224906/236861836-892c32f8-2dc5-408a-b99e-1983ca98c433.png)
