### ISSUE TITLE
sqlcmd -? not found

### ISSUE THREAD

**Issue by dzsquared** [microsoft/go-sqlcmd#384]
![image](https://github.com/microsoft/go-sqlcmd/assets/12227241/4d41921f-d2a3-4cea-be27-13b385318cac)

sqlcmd 1.1.0
macos 13.5

**Comment by stuartpa** [comment]
If the -? Is put in quotes does that fix the issue.

I think ? Might be a special character in the zsh she'll

**Comment by dzsquared** [comment]
Yep, that does it.
```
sqlcmd "-?"
```
provides output

**Comment by rwestMSFT** [comment]
For documentation purposes, is there a way to resolve this so that it provides output without the quotes? I'm hoping for something *useful* when a customer runs it on macOS as opposed to an error.

**Comment by shueybubbles** [comment]
`sqlcmd --version`  works for the Go sqlcmd if the goals are to tell if you are running it and to see what version it is.

**Comment by rwestMSFT** [comment]
@shueybubbles For the documentation, I want to say "Here's one command that works across all versions and platforms", and currently that's `sqlcmd '-?'`.

**Comment by stuartpa** [comment]
for go-sqlcmd, `sqlcmd --help` works across all versions and platforms.  Are you looking for a command that works across go-sqlcmd and ODBC sqlcmd?

**Comment by dlevy-msft** [comment]
This is the same behavior as the ODBC version due to the way mac os treats the ?.
