### ISSUE TITLE
Extra blank lines in stdout (breaking change)

### ISSUE THREAD

**Issue by arvindshmicrosoft** [microsoft/go-sqlcmd#40]
I am using sqlcmd to execute a script file which has 100 `CREATE DATABASE` statements, separated with a GO. A snippet of that file is provided at the end of this Issue. I observe that the console keeps scrolling upwards, presumably as a result of empty lines being returned to stdout.

Classic `sqlcmd` does not print any empty lines in this case. Hence, this is a breaking change for go-sqlcmd. Apart from a breaking change, it is a minor irritant when there is no real output expected from CR/D type statements like `CREATE DATABASE`. 

Command line being used:
```
sqlcmd.exe -i "C:/somepath/100dbs.sql" --authentication-method=ActiveDirectoryManagedIdentity -S someserver.database.windows.net
```

Snippet from SQL script file being used:
```sql
create database [3dprinting.meta.stackexchange]
go

create database [3dprinting.stackexchange]
go


create database [academia.meta.stackexchange]
GO

create database [academia.stackexchange]
GO

create database [ai.meta.stackexchange]
GO

create database [ai.stackexchange]
GO

create database [android.meta.stackexchange]
GO

create database [android.stackexchange]
GO

create database [anime.meta.stackexchange]
GO

create database [anime.stackexchange]
GO

create database [apple.meta.stackexchange]
GO

... script truncated for brevity
```

**Comment by shueybubbles** [comment]
is this on Windows, Linux, or both? 
I don't see it on my Windows run.

**Comment by arvindshmicrosoft** [comment]
OS Name	Microsoft Windows Server 2019 Datacenter
Version	10.0.17763 Build 17763

Code from this repo (commit hash 32462b7a4e59f35479550702032763ba1a66905a) built using `go build .\cmd\sqlcmd\`

**Comment by arvindshmicrosoft** [comment]
> is this on Windows, Linux, or both? I don't see it on my Windows run.

@shueybubbles the issue only reproduces if you have the batch separators (`GO`) with go-sqlcmd. In classic sqlcmd, the presence (or lack thereof) of the batch separator does not matter - a non-query statement will not print any extra newlines in the output in the classic sqlcmd.

**Comment by shueybubbles** [comment]
@arvindshmicrosoft  do you still see this?

This is what I get:

```
E:\git\go-sqlcmd\cmd\sqlcmd>type testdata\create100db.sql
create database db100
go

create database db101
go

create database db102
go
create database db103
go
create database db104
go
create database db105
go
create database db106
go
create database db107
go
create database db108
go
create database db109
go
create database db110
go
create database db111
go
create database db112
go
create database db113
go

E:\git\go-sqlcmd\cmd\sqlcmd>sqlcmd -i testdata/create100db.sql

E:\git\go-sqlcmd\cmd\sqlcmd>sqlcmd
1> select name from sys.databases
2> go
name
--------------------------------------------------------------------------------------------------------------------------------
master
tempdb
model
msdb
mydb
db100
db101
db102
db103
db104
db105
db106
db107
db108
db109
db110
db111
db112
db113

(19 rows affected)
```

**Comment by arvindshmicrosoft** [comment]
@shueybubbles I built with commit hash 1b77558b0ae8f11ad47169a9fe984be29de3c741 and I cannot reproduce the issue any more. Thanks for following up, I am closing the issue.
