### ISSUE TITLE
sqlcmd prints incorrectly strings

### ISSUE THREAD

**Issue by apoorvdeshmukh** [microsoft/go-sqlcmd#413]
The latest build prints erroneous strings.
```
>.\sqlcmd.exe stop
Stopping %!!(string=mcr.microsoft.com/mssql/server:latest)q(BADINDEX) for context %!!(string=mssql)q(BADINDEX)
```

**Comment by airtank20** [comment]
This message also occurs when issuing a "sqlcmd start": 

![image](https://github.com/microsoft/go-sqlcmd/assets/8907695/730578e9-9b8a-4ad0-85f5-a0eeaddb8a00)
