### ISSUE TITLE
Query results colorized but not the queries themselves

### ISSUE THREAD

**Issue by greenseeker** [microsoft/go-sqlcmd#417]
I've set SQLCMDCOLORSCHEME and when I run a query I now see the query results in color, but the queries themselves are still in plain white.

This is on Oracle Linux 8 and I've just installed the latest RPM from github. Is there another step required to enable this?

**Comment by shueybubbles** [comment]
Query colorization is limited to the output of `:list`
![image](https://github.com/microsoft/go-sqlcmd/assets/2224906/3e02fa80-9d03-453e-8f91-404769456eb4)

**Comment by greenseeker** [comment]
That's a bit strange, but ok. As long as I'm not just doing something wrong.
