### ISSUE TITLE
Release v1.2.1 does not publish windows installer package

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/go-sqlcmd#427]
Previous release v1.2.0 has 18 assets, one of which is an msi package, while v1.2.1 only has 10 assets. The only package available for Windows is a zip file.

**Comment by shueybubbles** [comment]
@stuartpa had you been uploading the MSIs manually?

**Comment by stuartpa** [comment]
v1.2.1 has been pushed to all package managers, Winget usually takes 24/48 hours to get through moderation (this PR will be merged automatically when moderation is complete):

https://github.com/microsoft/winget-pkgs/pull/112781

**Comment by stuartpa** [comment]
Winget PR is merged, 1.2.1 is available in winget.
