### ISSUE TITLE
Can't handle long strings

### ISSUE THREAD

**Issue by CaledoniaProject** [microsoft/go-sqlcmd#437]
What should I do with bufio.scanner: token too long? Can you use a unbuffered reader?

**Comment by shueybubbles** [comment]
Can you please provide the steps to reproduce the issue? Is it with interactive mode or from an input file or both?

**Comment by CaledoniaProject** [comment]
I just run `sqlcmd -S XXX -C -i XXX.sql` and it prints tons of bufio error. The ubuntu sqlcmd binary package does not suffer from this.

**Comment by shueybubbles** [comment]
For any size of xxx.sql? Or for a certain batch size inside the file? 
What OS and sqlcmd version combination are you using?

**Comment by CaledoniaProject** [comment]
I have completely no idea, because you're not printing the line number. I also think you don't have to know the size of the SQL file. 

1. You're using a fixed buffer size: https://github.com/microsoft/go-sqlcmd/blob/main/pkg/sqlcmd/sqlcmd.go#L42
2. The solution is easily found on stackoverflow: https://stackoverflow.com/questions/21124327

**Comment by CaledoniaProject** [comment]
If you want to produce the issue, you could create a large blob, e.g 100MB to test it.

**Comment by shueybubbles** [comment]
thx for the pointer, we'll take a look
