### ISSUE TITLE
Add support for Azure AD device code authentication

### ISSUE THREAD

**Issue by maskati** [microsoft/go-sqlcmd#449]
Currently `--authentication-method` supports `ActiveDirectoryInteractive` which uses [azidentity.InteractiveBrowserCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#InteractiveBrowserCredential). This limits usage to windowed environments with a web browser.

Consider supporting a new authentication method `ActiveDirectoryDeviceCode` which would use [azidentity.DeviceCodeCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#DeviceCodeCredential).

**Comment by shueybubbles** [comment]
thx for opening an issue!
We need to add this method to the [driver](https://github.com/microsoft/go-mssqldb) first.

**Comment by maskati** [comment]
Now that i think about it, *even better* would be support for [AzureCliCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#AzureCLICredential), which would allow using an ambient Azure CLI authenticated context (which supports device code authentication) in an SSO manner. Support for this would mean no need to authenticate sqlcmd at all if Azure CLI was already authenticated, which it often is. Should this be a separate request?

**Comment by shueybubbles** [comment]
`--authentication-method ActiveDirectoryDefault` includes `AzureCliCredential` in the search

**Comment by maskati** [comment]
@shueybubbles great! I didn’t notice that since i assumed `ActiveDirectoryDefault` was a combination of the other methods directly supported by go-sqlcmd rather than those supported by azidentity.

**Comment by farshid3003** [comment]
Are you going to solve this?

**Comment by shueybubbles** [comment]
we added azcli and device code here https://github.com/microsoft/go-sqlcmd/commit/0a4cd1949a9ff220649a4f7bd0d9f775488df8e1#diff-8b63f3c9b8211c5793c8ac1aa5113aae3858130effb2401bcb8364e8664ce62d
