### ISSUE TITLE
apt-get needs manual intervention to accept the licenese

### ISSUE THREAD

**Issue by scott-doyland-burrows** [microsoft/go-sqlcmd#460]
When installing on Ubuntu, apt-get asks for a manual confirmation of the license agreement.

I want to automate the installation so need to do something similar to this:

https://stackoverflow.com/questions/19275856/auto-yes-to-the-license-agreement-on-sudo-apt-get-y-install-oracle-java7-instal

What are the ```debconf``` commands I need to automate the acceptance of the license.

Automated installations should always be documented.  

Thanks.

**Comment by stuartpa** [comment]
I just tried this and I don't get asked for a manual confirmation of the license agreement

apt-get install sqlcmd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  sqlcmd
0 upgraded, 1 newly installed, 0 to remove and 125 not upgraded.
Need to get 0 B/5242 kB of archives.
After this operation, 19.3 MB of additional disk space will be used.
Selecting previously unselected package sqlcmd.
(Reading database ... 32479 files and directories currently installed.)
Preparing to unpack .../sqlcmd_1.2.1-1~buster_all.deb ...
Unpacking sqlcmd (1.2.1-1~buster) ...
Setting up sqlcmd (1.2.1-1~buster) ...

Can you share your output?

**Comment by stuartpa** [comment]
Closing, waiting for OP to share output of manual intervention (I'm not seeing this locally)
