### ISSUE TITLE
Sporadically can't find instance in availability group

### ISSUE THREAD

**Issue by sliekens** [microsoft/go-sqlcmd#462]
Hello,

I intermittently get an error with sqlcmd v.1.2.1 when connecting to an instance in a high availability cluster.

> no instance matching 'inst01' returned from host 'redacted'

This sounds to me like an issue with MultiSubnetFailover. I removed `-M` from my sqlcmd command because it has been deprecated, but I didn't have this problem with the ODBC version of sqlcmd (with `-M`).

My full command is something like:

``` sh
sqlcmd -S 'redacted\inst01' -d 'redacted' -U 'redacted' -P '****' -b -i 'script.sql'
```

OS: Debian 11 running inside Docker

Thanks for your attention.

**Comment by sliekens** [comment]
@shueybubbles no problem (I removed some portion of IPs because I don't know who else is reading this)

```
DRIVER:unable to get instances from Sql Server Browser on host redacted: read udp 172.23.x.x:46208->10.208.x.x:1434: i/o timeout
DRIVER:Skipping protocol tcp. Error:no instance matching 'inst01' returned from host 'redacted'
```

Do you know what it means?

**Comment by shueybubbles** [comment]
`1434` is the SQL Browser service port. The driver tries to query the browser service on that port to get the port number for `inst01`.
If you know the port number for `inst01` you could change your connection string to use it directly instead of using the instance name, it will speed up the connection a bit.
Alternately try increasing the dial timeout.

**Comment by sliekens** [comment]
Thanks. I was told the port for `inst01` is 50001. Do you have any insight what the connection to port 60000 could be?
How would I increase the dial timeout? Is it the `-l` option?

**Comment by shueybubbles** [comment]
I don't know what 60000 would be.
`-l` is the dial/connect timeout

**Comment by sliekens** [comment]
Just gonna close this as I'm waiting for krb5 support to switch from old sqlcmd to sqlcmd-go. It was probably an environmental issue anyway.
