### ISSUE TITLE
sqlcmd -L command return strange strings

### ISSUE THREAD

**Issue by AnyiYang** [microsoft/go-sqlcmd#474]
My customer runs sqlcmd -L and it returns strange string like following:

Servers:
    ;UID:Login ID=?;PWD:Password=?;Trusted_Connection:Use Integrated Security=?;*APP:AppName=?;*WSID:WorkStation ID=?;

The issue can be reproduced in my server with sqlcmd shipped with SQL 2019, SQL 2022. The issue also exists when I use go-sqlcmd:

C:\Windows\System32>sqlcmd -?

Version v1.4.0

C:\Windows\System32>sqlcmd -L

Servers:
    ;UID:Login ID=?;PWD:Password=?;Trusted_Connection:Use Integrated Security=?;*APP:AppName=?;*WSID:WorkStation ID=?;

I debuged the sqlcmd shipped with SQL 2022. The issue is that when sqlcmd tries to fetch server list from return result of SQLBrowseConnectW of driver (this is msodbcsql), it could not handling well when there is no server name between { and } in the result. But I think go-sqlcmd might not use msodbcsql. Not sure if it also hit the same string handling problem. Please help to have a check on the issue.

**Comment by shueybubbles** [comment]
go-sqlcmd doesn't implement a real browse, it always returns the same string that ODBC sqlcmd prints when the list is empty. See https://github.com/microsoft/go-sqlcmd/blob/7002492d79c93015a7c28988e4284c62205e5da0/cmd/sqlcmd/sqlcmd.go#L219

I just assumed whatever ODBC sqlcmd printed was correct.

**Comment by shueybubbles** [comment]
i can fix sqlcmd to use the browser service locally, at least. But I would keep backward compatibility for the empty case.

**Comment by stuartpa** [comment]
@AnyiYang -> can you provide some details on what your customers is using -L for.  Is it just to enumerate the local instances on the machine, or something else?
