### ISSUE TITLE
Hangs when calling SP that uses a cursor

### ISSUE THREAD

**Issue by IGx89** [microsoft/go-sqlcmd#48]
Any time I attempt to call a stored proc that iterates over a cursor, the tool hangs. Using this command:
```
sqlcmd -Q "exec TestSqlCmd" -S "DatabaseServer" -U DatabaseUser -d DatabaseName
```
and the following variations of the stored proc:
```tsql
CREATE PROCEDURE [dbo].[TestSqlCmd]
AS
BEGIN
	DECLARE @tmp int;

	DECLARE Server_Cursor CURSOR FOR
	SELECT 1 UNION SELECT 1

	OPEN Server_Cursor;
	FETCH NEXT FROM Server_Cursor INTO @tmp;
	WHILE @@FETCH_STATUS = 0
		BEGIN
			FETCH NEXT FROM Server_Cursor INTO @tmp;
		END;
	CLOSE Server_Cursor;
	DEALLOCATE Server_Cursor;
END

GO
```
```tsql
CREATE PROCEDURE [dbo].[TestSqlCmd]
AS
BEGIN
	DECLARE @tmp int;

	DECLARE Server_Cursor CURSOR FOR
	SELECT 1 UNION SELECT 1

	OPEN Server_Cursor;
	CLOSE Server_Cursor;
	DEALLOCATE Server_Cursor;
END

GO
```
The command hangs indefinitely. Strangely, if I remove the DEALLOCATE like so it works:
```tsql
CREATE PROCEDURE [dbo].[TestSqlCmd]
AS
BEGIN
	DECLARE @tmp int;

	DECLARE Server_Cursor CURSOR FOR
	SELECT 1 UNION SELECT 1

	OPEN Server_Cursor;
	CLOSE Server_Cursor;
END

GO
```
but if I attempt doing so with the full SP it still hangs:
```tsql
CREATE PROCEDURE [dbo].[TestSqlCmd]
AS
BEGIN
	DECLARE @tmp int;

	DECLARE Server_Cursor CURSOR FOR
	SELECT 1 UNION SELECT 1

	OPEN Server_Cursor;
	FETCH NEXT FROM Server_Cursor INTO @tmp;
	WHILE @@FETCH_STATUS = 0
		BEGIN
			FETCH NEXT FROM Server_Cursor INTO @tmp;
		END;
	CLOSE Server_Cursor;
END

GO
```
Every single one of the variations above work just fine using the standard `sqlcmd` tool. I've tested on a local SQL Server database and an Azure SQL Server database with same results, so it doesn't appear to be server-specific.

**Comment by shueybubbles** [comment]
@IGx89 can you try it with an earlier preview build to see if perhaps it was broken by https://github.com/microsoft/go-sqlcmd/commit/facd5a00ef224c33afcb8b8611a8f28e4878e7f1

**Comment by IGx89** [comment]
@shueybubbles your theory is correct, this issue doesn't happen on v0.2.0. I'll use that version until this bug is fixed, thanks a lot for the workaround!

**Comment by shueybubbles** [comment]
opened a PR for the driver fix https://github.com/denisenkom/go-mssqldb/pull/723

**Comment by shueybubbles** [comment]
Please try version v0.4.0

**Comment by IGx89** [comment]
> Please try version v0.4.0

Confirmed working, thank you!
