### ISSUE TITLE
Scripting variables are not expanded in :out and :r commands

### ISSUE THREAD

**Issue by scara** [microsoft/go-sqlcmd#522]
Hello Everyone,
in `mssql-tools` a SQL script can use variables even when composing a file path in `:out` and `:r` commands.

The `go` version is not able to expand variables in the _filename_ of these commands:
```
:on error exit
:setvar WorkingDir ./tmp
:out $(WorkingDir)/file.sql
GO
PRINT '-- Test file.'
GO
:out stdout
GO
:r $(WorkingDir)/file.sql
GO
```
and leads the SQL script above to the following errors:
```
Sqlcmd: Error:  Error occurred while opening or operating on file $(WorkingDir)/file.sql (Reason: open $(WorkingDir)/file.sql: no such file or directory).
Sqlcmd: Error:  Error occurred while opening or operating on file $(WorkingDir)/file.sql (Reason: open $(WorkingDir)/file.sql: no such file or directory).
```
Tested on both `v1.5.0` and `v1.6.0`.

TIA,
Matteo

**Comment by shueybubbles** [comment]
thx for opening an issue! Is the support for variables supposed to be for all commands, or just ones that take file paths?

**Comment by shueybubbles** [comment]
`:r' works for me, but ':out' and ':error' are definitely broken

**Comment by scara** [comment]
Hi @shueybubbles,
> `:r' works for me, but ':out' and ':error' are definitely broken

Didn't test them separately, just on top of my use case.

Thanks a ton for the PR!
Matteo
