### ISSUE TITLE
BCP supports with ODBC Driver 18

### ISSUE THREAD

**Issue by mikependon** [microsoft/go-sqlcmd#526]
We are using the BCP utility to bulk insert huge number of rows towards our Data Lake Data Warehouse (a dedicated SQL Pool in Azure) and it is kind of a very important capability to us.

The current released version of [BCP](https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16) is only supporting the [ODBC Driver v17](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#version-17).

![image](https://github.com/microsoft/go-sqlcmd/assets/591015/5dbf925f-537e-448a-b701-364d18447977)

Our organization has already started the rollout of the [ODBC Driver v18](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#download-for-windows) to complement the requirement of Security Vulnerabilities.

Though we can still utilize the BCP in our Azure Kubernetes Services by just referencing the older version of `mssqltools17` as defined [here](https://github.com/microsoft/mssql-docker/blob/master/linux/mssql-tools/Dockerfile.debian11), but still it fails to run from various Windows-based platform now where has the updated ODBC drivers.

Is there a plan to support the latest ODBC driver v18? And if yes, when do we expect it? Thanks

**Comment by matthewhilldev** [comment]
Hey @shueybubbles is there any chance you could look into this? ODBC v17 has CVEs our company is wanting to address by updating to v18.
Thanks!

**Comment by dlevy-msft** [comment]
Hey @matthewhilldev - It's a bit outside the scope of this work here, but there were breaking changes between ODBC 17 and 18 around connection security. To allow customers to phase in this change, BCP 18 has a different path than BCP 17 so they can run side by side. The BCP you use must be the same version as the drivers installed so BCP 17 uses ODBC 17 and BCP 18 uses ODBC 18. Here is a link for the various downloads: https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16&tabs=windows#download-the-latest-version-of-the-bcp-utility

Here is an additional article on using Entra auth with BCP in case you haven't run across it yet: https://learn.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver16&tabs=windows

**Comment by shueybubbles** [comment]
not relevant for this repo
