### ISSUE TITLE
:SETVAR with a comment on the same line throws syntax error

### ISSUE THREAD

**Issue by BradKnowles** [microsoft/go-sqlcmd#546]
If you have a line like so

`:setvar RedeployJobs "YES"     -- "YES" to redeploy jobs, "NO" to skip redeploy`

A syntax error results

```
Sqlcmd: Error: Syntax error at line X near command ':SETVAR'.
Sqlcmd: Error: Syntax error at line X near command ':SETVAR'.
```

**Comment by LarnuUK** [comment]
Huh, I was about to report a similar problem in regards to `[:]QUIT`. In sqlcmd ODBC, the following will cause `QUIT` to work:
```sql
PRINT 1;
:QUIT --This is a test
```
So, for example, sqlcmd ODBC version 15.0.1300.359 won't provide an output. Using sqlcmd Go v1.8.0, however, you get similar to the OP:
```none
Sqlcmd: Error: Syntax error at line 2 near command 'QUIT'.
1
```
Enabling the `-b` switch causes the error to be repeated:
```none
Sqlcmd: Error: Syntax error at line 2 near command 'QUIT'.
Sqlcmd: Error: Syntax error at line 2 near command 'QUIT'.
```
