### ISSUE TITLE
'reset' command not supported

### ISSUE THREAD

**Issue by robverschoor** [microsoft/go-sqlcmd#552]
The ODBC version of `sqlcmd `supports the `reset `command, which discards the batch (as opposed to `go`, which sends the batch to the server).
The Go version of `sqlcmd `does not seem to support reset, but my scripts use it. Please add support for `reset`?

**Comment by shueybubbles** [comment]
@robverschoor both versions support `:reset`
The ODBC inconsistency with which commands require the `:` was somewhat difficult to replicate. The documentation I was using didn't mention this as optional for `:reset`, at least at the time

**Comment by robverschoor** [comment]
This is about `reset` without a leading colon (like `go` or `exit`). I have existing scripts containing `reset`.

**Comment by shueybubbles** [comment]
yes I was just mentioning a source of the disconnect.
