### ISSUE TITLE
Backslashes in cmdline-option arguments causes option to be ignored

### ISSUE THREAD

**Issue by sommarskog** [microsoft/go-sqlcmd#66]
When I try:

sqlcmd -S SERVER\INSTANCE

all that happens is that I get the command-line prompt again. SQLCMD does not start and there is no error message. It does not matter if the server or instance exists, behaviour is the same.

In the same vein, if I do:

sqlcmd -i C:\temp\slask.sql

The result is the same. That is, SQLCMD does not start, and there is no error message. Again, it does not matter if the file exists or not.

I don't know these are two separate defects or tokens of the same issue, but submit it as a single one.

**Comment by shueybubbles** [comment]
The second one is #39 
The first one is probably related to 39. I suspect you can work around it by setting SQLCMDSERVER instead of passing it on the command line.
