### ISSUE TITLE
sqlcmd -? does not work and -h does the wrong thing.

### ISSUE THREAD

**Issue by sommarskog** [microsoft/go-sqlcmd#67]
If I run `sqlcmd -?` with the established SQLCMD I get a list of option. If I run this with go-sqlcmd, I get:

sqlcmd: error: unknown flag -?, did you mean one of "-h", "-c", "-C", "-d", "-E", "-U", "-i", "-o", "-q", "-Q", "-S", "-X", "-G", "-x", "-v", "-a", "-l", "-H", "-K", "-N", "-b", "-V", "-m", "-F", "-r"?

`sqlcmd -h` or `sqlcmd --help` gives the desired result. However, `-h` has an established meaning with SQLCMD to specify how often you want headers printed. I would guess that there quite a few bat files out there with `SQLCMD -h-1` in them. These are people who use SQLCMD to export data and the argument -1 suppresses the headers entirely.

`--help` can still be used for help, but it is not a good idea to use `-h`.

**Comment by shueybubbles** [comment]
`-h` is Kong's default shortcut for help, I'll see how to change it to ?
