### ISSUE TITLE
Bad alignment of result set.

### ISSUE THREAD

**Issue by sommarskog** [microsoft/go-sqlcmd#69]
The screenshot below says it all:

![image](https://user-images.githubusercontent.com/29492491/161443857-0606be79-64ac-4f4a-8d77-cf2a611734a0.png)

**Comment by shueybubbles** [comment]
heh where did UnitPrice go?

**Comment by shueybubbles** [comment]
and why do SQL Server tools left-align numbers?

**Comment by shueybubbles** [comment]
we're missing formatting data for `MONEY`
