### ISSUE TITLE
The presentation of date/time data types needs some polishing

### ISSUE THREAD

**Issue by sommarskog** [microsoft/go-sqlcmd#77]
I would guess this is on a to-do-list, but I file it never the less.

The presentation of datetime values is a little funny as demonstrated by the screenshot below.

- For datetime, +00 is added if the fraction is 0.
- For datetime, no trailing zero is printed when last digit in fraction is 0.
- For date, hours and minutes are printed.
- For datetime2 a +0000 UTC is added that should not be there.
- For datetime2(3) .000 is not printed.
- For time a date of 0000-01-01 is added. Likewise a time zone which should be there is added.

![image](https://user-images.githubusercontent.com/29492491/162636061-7bac60b9-850f-499d-884d-d06f071ff082.png)

**Comment by shueybubbles** [comment]
data types in go's `sql/driver` model are "basic" at best. I think the scan converts all these to `time.Time` instances. We'll need to check the SQL datatype name as well and format them accordingly.

**Comment by shueybubbles** [comment]
BTW our "to do" list right now is this Issues forum :-)
One caveat is there's a fair number of command line switches from the old sqlcmd we haven't implemented yet and there aren't individual issues for those.

**Comment by shueybubbles** [comment]
the ODBC sqlcmd seems to use bigger-than-necessary widths for date and time columns. Why 22 characters for "time" ? Isn't 14 enough?

**Comment by sommarskog** [comment]
I don't want to intercept in the planning, so will I not complain about unimplemented switches. :-)

For time(7) you need 16 characters, spacing to next column not included. 22 seems too much.

**Comment by shueybubbles** [comment]
If there are certain missing command line switches you'd like us to implement first, please open issues accordingly! We appreciate your usage and input!
