### ISSUE TITLE
-F does not really work

### ISSUE THREAD

**Issue by sommarskog** [microsoft/go-sqlcmd#78]
sqlcmd -F="horiz"

results in

sqlcmd: error: --format must be one of "horiz","horizontal","vert","vertical" but got "=horiz"

It works with --format, though.

**Comment by shueybubbles** [comment]
short switches don't use `=`

```
E:\git\go-sqlcmd\cmd\sqlcmd>.\sqlcmd -F vert
1> select 100 as count, 'what' as what
2> go
count 100
what  what


(1 row affected)
```
